name: ReadmeBot

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to master branch
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2.3.0
        with:
          node-version: "18.x"
      - name: Cache dependencies and build outputs
        uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node index.js
        env:
          UNSPLASH_ACCESS_KEY: ${{secrets.UNSPLASH_ACCESS_KEY}}
      - name: Commit and push new README.md
        run: |-
          git diff
          git config --global user.email "${{secrets.GLOBAL_USER_EMAIL}}"
          git config --global user.name "${{secrets.GLOBAL_USER_NAME}}"
          git commit -a -m "Daily Update" || exit 0
          git push
